export const BUSINESS_TYPES = [
  "Retail Shop",
  "Grocery/Supermarket",
  "Restaurant/Food",
  "Drinks/Bar",
  "Bakery",
  "Butchery",
  "Fruits & Vegetables",
  "Salon/Beauty",
  "Barber Shop",
  "Clothes/Fashion",
  "Electronics",
  "Mobile Money Agent",
  "Pharmacy",
  "Hardware",
  "Agriculture",
  "Transport",
  "Services",
  "Other",
];